id: PAD0D0C18
initial_creation_type: input
source_metadata:
  title: Mipham Rinpoche Series
  language: de
  description: 'Texts by and about the great Nyingma polymath Jamgön Mipham Namgyal
    Gyatso (mi pham rnam rgyal rgya mtsho, 1846-1912), arguably the most influential
    Tibetan scholar of recent times:'
  volume:
    9f39715393234d0ba01bd8a266b73da5:
      title: Advice for Beginners
      parent: Advice
    a48a9f959247461aae8fe08964588f9e:
      title: Advice to Jigme Tenpe Nyima
      parent: Advice
    c3b08159248947a4a26900beb3a1f56a:
      title: Essence of the 84000 Approaches to the Dharma
      parent: Advice
    b8b3edb5ef3b4b019b2d9fa684a7c884:
      title: How to Cultivate Concentration
      parent: Advice
    5b4ca77344e24524bef1fb4e3b9b4ca4:
      title: Profound Instruction on Śamatha
      parent: Advice
    95df7b3bee6e4270b41631c8ac623c46:
      title: Satirical Advice for the Four Schools
      parent: Advice
    406bda3918a244c88b920be4a843db71:
      title: The Four Dharma Traditions of Tibet
      parent: Advice
    9631811d5c0e4899a865f954e0847229:
      title: The Mahāmudrā Practice of Stillness, Movement and Awareness
      parent: Advice
    07c02a7289ba407eb3b83ad5aec92d6a:
      title: The Perfect Equality of the Dharmadhātu
      parent: Advice
    7421e2fb95e04be4b394f29ceda1d3c4:
      title: A Brief Prayer for Summoning Prosperity
      parent: Aspiration Prayers
    89f64bebb6aa455fbf7fb3ab849ddfe5:
      title: Aspiration for the Four Activities
      parent: Aspiration Prayers
    914d2c2551d44a1c811539edc2b3cdbc:
      title: Light Offering Prayer
      parent: Aspiration Prayers
    7c08e4dc44a24704bda7705d5b64e64f:
      title: Sukhāvatī Aspiration
      parent: Aspiration Prayers
    7f0c59c2db0e4114b70db89fcd6a9f5f:
      title: Summoning the Spirit of Abundance - The Hook of Divine Substance
      parent: Aspiration Prayers
    69422fc1052340cc9359c40c0fee6739:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Aspiration Prayers
    2738350c27e94ddf9f0da76e1145b6d1:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Aspiration Prayers
    2dcb0b2f6b6a4672b051494a41c1a370:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Aspiration Prayers
    c99ab37240e34ca3a4eab02c30f94c6c:
      title: A Brief Version of the 'Chinese' Practice of Averting Periodic Obstacles
      parent: Averting Obstacles
    aadf0384f3cc4e0d9c9c08fb1f4e4f78:
      title: Benedictory Verses for A Brilliant Elucidation of Logical Reasoning
      parent: Benedictory Verses
    1f698e4db52a47019e2f9a06af8c9d9d:
      title: Benedictory Verses for White Lotus
      parent: Benedictory Verses
    609f7d19d7b8475484ef9e249f2a01db:
      title: Ascertaining the Two Kinds of Selflessness
      parent: Buddhist Philosophy
    0aea7a8e2e934436ba461d73f14dece8:
      title: 'Gateway to Learning: Four Great Logical Arguments of the Middle Way'
      parent: Buddhist Philosophy
    4dc5d30bee9741ac8e8d175ba066fd1b:
      title: 'Gateway to Learning: Individual Selflessness'
      parent: Buddhist Philosophy
    e609d6cd736f40198b7f2981d24ff206:
      title: Profound Instruction on the View of the Middle Way
      parent: Buddhist Philosophy
    9baa8712eb9545f1beddb58011e41ebd:
      title: Putting the Instruction on the Purification of Mental Activity into Practice
      parent: Buddhist Philosophy
    79e3ebb3f0ea44e4879a919fb1f4be76:
      title: The Sword of Wisdom for Thoroughly Ascertaining Reality
      parent: Buddhist Philosophy
    1e1edebc9ba44b4c80d6840099307cf3:
      title: 'The Vajra Mirror: Cutting through Doubts Concerning Self-Awareness'
      parent: Buddhist Philosophy
    fa98790c97b14550998472f24f3462c6:
      title: The Wheel of Analytical Meditation That Thoroughly Purifies Mental Activity
      parent: Buddhist Philosophy
    cb8443509e50463d8818ed80d38614f7:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Dharma Protectors
    1844ae9ec20f451d9388cf18b8c8e51b:
      title: Brief Offering Prayer to Ekajaṭī
      parent: Dharma Protectors
    18603d6272d746709c0b2c1345f0dafe:
      title: Brief Offering Prayer to Tsiu Marpo
      parent: Dharma Protectors
    3af82a86cd5a4fe2a981c4db5ada4a22:
      title: Brief Offering Prayer to Za Rāhula
      parent: Dharma Protectors
    59790384a795478e9361c102d44544b3:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      parent: Dharma Protectors
    df094c9e2bd6458f8a8d9932b1d3e478:
      title: Offering to the Five Medicine Sisters, Guardians of the Earth
      parent: Dharma Protectors
    34292474b9fc4f338295e5fd8af14b56:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Dzogchen
    f1df17bebf664709a310462abafa3390:
      title: Pith Instruction on the Three Crucial Statements
      parent: Dzogchen
    c42d06ad600d420194416ce97213ce2e:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Dzogchen
    e8531dd95e7e4712942cd3d7b452abc5:
      title: The Essence of Mind
      parent: Dzogchen
    1fbfb317a51b4c88ad4ff219e8411fb0:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Dzogchen
    420b22ff47894df3a41405ce5eb225e4:
      title: The Key Points of Trekchö
      parent: Dzogchen
    0a83eb57fa78488cbbdea20767f341a0:
      title: The Nature of Mind
      parent: Dzogchen
    a6ffe8d7dca9475bbf0bb6f0a4400482:
      title: Brief Gesar Windhorse Invocation
      parent: Gesar
    633116d6b87f4dbd99f1d5195b37bce2:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    298d60d1f2354f3f8c28e4168a0eb8dd:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Gesar
    b5ee923ddbdf42fba3f62890409c31d9:
      title: Prayer to Gesar
      parent: Gesar
    5b48872c6c054e81bfc4abf6ec77c109:
      title: Short Windhorse Prayer to Gesar
      parent: Gesar
    9f55974424c84ca7b8a16c997e0b64c3:
      title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
        Accomplishes Activities
      parent: Gesar
    40f89e5611b74319a7634bda15ed1173:
      title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King
        of the Dralas'
      parent: Gesar
    c605ddcb1d2b47b88e4e157f00609271:
      title: The Swift Accomplishment of Enlightened Activity through Invocation and
        Offering
      parent: Gesar
    4231ecc58bb44e1db7913e14a5dc1d15:
      title: 'The Swift Fulfilment of Wishes: A Brief Offering Prayer to King Gesar'
      parent: Gesar
    917d70337b3c477d9cd2cc3f6032610b:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Gesar
    c0e5f68cfd744d428027810d15dce7b7:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line
        Prayer (Addendum)'
      parent: Guru Yoga
    194a7fd92c064eb0b65e43e840416563:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven-Line
        Prayer'
      parent: Guru Yoga
    93611791b2824841967c4d052809f009:
      title: 'A Shower of Wisdom: A Guru Yoga of Garab Dorje'
      parent: Guru Yoga
    efe3ffe7283d482fa0a78faa25219471:
      title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
      parent: Guru Yoga
    900d497e89aa4d5891b1f6f5898b5d6a:
      title: Guru Yoga Focusing upon Noble Kurukullā
      parent: Guru Yoga
    0bf956c1e0cc4363ab82cebce4929712:
      title: 'Shower of Blessings: A Guru Yoga of the Great Paṇḍita, Glorious Rongzom'
      parent: Guru Yoga
    4af675fa6c204c1985d2163a390609c7:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Guru Yoga
    ee1eef5c6aec4545a3fe6a29c64159a8:
      title: Short Sang Offering to Kurukullā
      parent: Kurukullā
    efe1c9d2376a4f89a87ef86a8ae2055a:
      title: Short Torma Offering to Kurukullā
      parent: Kurukullā
    11b1e05a34e444d09aa0b65f01924431:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      parent: Kurukullā
    6999dc0285bb4d4bbef8eca2a4cc2b45:
      title: Brief Dzogchen Lineage Prayer
      parent: Lineage Prayers
    093741850bf144b3b4a32b6a85335f89:
      title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
      parent: Lineage Prayers
    6321d0ed5e2c4c70b5d3e37ebc776676:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      parent: Long Life Prayers
    90efe49e71dd456ba0f9cf83b8510294:
      title: Extemporary Practice of Longevity for Oneself or Others
      parent: Longevity
    70a9cc8a691446ad83053c0459202466:
      title: Brief Windhorse Invocation
      parent: Lungta
    1a9fb17b44a543c2bfcdd5476dc03315:
      title: Daily Lungta Recitation
      parent: Lungta
    04f2679d82f44c26bc53e8d6e085cab6:
      title: The Swift Fulfilment of All Wishes—Offering the Flag of Windhorse
      parent: Lungta
    77f170276fe44930bce1007b86bd0e22:
      title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
      parent: Mantras
    3c98d3a61ffe4fac8a3cd1fee1866e1e:
      title: Wrathful Guru Mantra Visualization
      parent: Mantras
    3481906d636748af90756279081d43d4:
      title: 'The Wish-Granting King of Jewels: An Essential Garland of Offerings'
      parent: Offering
    292aeee6c30945ca86bbe67a77c56d6e:
      title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
      parent: Praise
    fd2db6506f04432e9b269cfbce301de7:
      title: 'Gentle Splendour: Praises to the Great Abbot Śāntarakṣita'
      parent: Praise
    53cb1d27e55545cbb70feeaf02c7105f:
      title: 'Snowy Lands: Praises to the Great Dharma Emperor Tri Songdetsen'
      parent: Praise
    b0a5669209344ab5bbe4607aa97a2ae5:
      title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
      parent: Praise
    bba1f6ae1317487cac48d140255af743:
      title: Prayer Recalling the Life and Liberation of the Mañjunātha Guru
      parent: Prayers
    ac085effb4b04b33b223ee4f88835ec8:
      title: Prayer to Akṣobhya
      parent: Prayers
    b7922c9728404fda9f71d067aacb1816:
      title: Prayer to Smṛtijñānakīrti
      parent: Prayers
    4da362736d9742a8a105f22560660ecd:
      title: Three Prayers from the Earth Pig Year
      parent: Prayers
    85cf3b87933b40128b83c14c590aa15a:
      title: 'Wangdü: The Great Cloud of Blessings—The Prayer which Magnetizes All
        that Appears and Exists'
      parent: Prayers
    5677b115272c4c17ae496da270bc328c:
      title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
      parent: Prayers to Guru Rinpoche
    a335d5a413e94118ad2e23c797af0d7b:
      title: Recollecting the Deeds of The Tenth Days
      parent: Prayers to Guru Rinpoche
    7c54344e695147bf813f53e0bcd7dd3f:
      title: The Prayer which is the Source of All True Realization
      parent: Prayers to Guru Rinpoche
    29a2fa64e98e4615b080dcd7b706e4a0:
      title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
      parent: Prayers to Mañjuśrī
    8116cfdc430345bd8ae5f837c70e8a13:
      title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
      parent: Prayers to Mañjuśrī
    8cc0c18298204706aa86c2de1cddb20e:
      title: In Praise of the Protector Mañjughoṣa
      parent: Prayers to Mañjuśrī
    d618f18bb384497b9eb2548fc7041abe:
      title: Prayer to Mañjuśrī
      parent: Prayers to Mañjuśrī
    d12c7f350ddc4e048c03f52cc5a191f8:
      title: Prayer to the Sovereign of Dharma and Retinue
      parent: Prayers to Śākyamuni
    4b2c14af469445f28598e4e0c12d83fd:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Prayers to Śākyamuni
    be7a5d41bc894ee78246311e4b6bc5d5:
      title: 'Illuminating the Path to Liberation: A Preliminary Practice (Ngöndro)'
      parent: Preliminary Practice
    b7a051353aa5439e8b814b9f3c5f3238:
      title: A Sādhana of Jambhala
      parent: Sādhanas
    3bb5b23d6d4b4e50a921b0006aabf72c:
      title: A Sādhana of Kurukullā
      parent: Sādhanas
    5ce3b8b996bd40448b7cba63183779f0:
      title: A Sādhana of Sitātapatrā
      parent: Sādhanas
    4c14d5616c214eb4a6622b67bd93e7cc:
      title: A Sādhana of White Sarasvatī
      parent: Sādhanas
    adb00faeb22048ba8105acfd85c10103:
      title: Acala Sādhana
      parent: Sādhanas
    80b70cf735e843faa183ac69e6493a8e:
      title: Kṣitigarbha Visualization and Mantra Recitation
      parent: Sādhanas
    83211e5ad2f44aeebf287c5a221b39cc:
      title: Sādhana of Mārīcī
      parent: Sādhanas
    a0723fdae98c452bae808a51a43db107:
      title: Visualization and Recitation of the Six-Syllable Mantra of Avalokiteśvara
      parent: Sādhanas
    5753528bc4d24ab2937f57572603612a:
      title: Brief Sang Offering
      parent: Sang Offering
    b0fe4499c5684ccdbb733c0c011a5999:
      title: Brief Sang Offering to Purify Contamination
      parent: Sang Offering
    dd73ff0243684e34a3b30fd40877e470:
      title: 'The Glorious Gift of Longevity and Granting All Desires: A Liturgy for
        Saving Lives'
      parent: Saving Lives
    e9999595928d4aee843b8084f8b9ed32:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    e03f71a477714f1baf2f0816f74129c0:
      title: 'Freedom from All Adversity: A Sur Offering to Harmful Influences, Obstacle-Makers
        and Elemental Spirits'
      parent: Sur Offering
    a7375a44600c4cbebced6fa14666de4e:
      title: Prayer to Tārā, Combined with Her Mantra
      parent: Tārā
    5d93e6290b9d4cd49fea1e64bf36195e:
      title: Outline of the Ten Royal Sūtras
      parent: Topical Outlines
    2796cb058c944df7a9c8d75498e412cf:
      title: Concise Tsok Feast
      parent: Tsok
    7f5145a7a1ab4699b9df029e7d96d5cc:
      title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the
        Vajra Seven-Line Prayer'
      parent: Tsok
    03089ac6785a457a8a18054f84e745ee:
      title: A Method of Purifying Samaya Violations by Relying on the Glorious Guru
        Vajrasattva
      parent: Vajrasattva
created_at: '2022-03-01T00:57:12.440781'
last_modified_at: '2022-03-01T00:57:12.440785'
